### ISSUE TITLE
Sign Up or Login?

### ISSUE THREAD

**Issue by yasbaswork** [Evertrix/Twitter#3]
Also on the login form, should the user "choose" a password or "enter" it, as it's already been chosen?
<img width="1289" alt="Screen Shot 2019-12-31 at 10 04 03 AM" src="https://user-images.githubusercontent.com/2727591/71614573-20590000-2bb5-11ea-8e88-cc308b7268d2.png">

Copy/pasting code is a double-edged knife. It saves you time, but it can also lead to stupid errors when not edited properly after pasting...

**Comment by Evertrix** [comment]
It is fixed.

**Comment by yasbaswork** [comment]
Next:

<img width="994" alt="Screen Shot 2020-01-16 at 9 57 36 AM" src="https://user-images.githubusercontent.com/2727591/72508116-c6f7fe80-384d-11ea-9c90-ecec02498929.png">

**Comment by Evertrix** [comment]
Now fixed on login page and register page.

**Comment by yasbaswork** [comment]
OK. Good.
