### ISSUE TITLE
Do not create the database in the SQL setup file

### ISSUE THREAD

**Issue by yasbaswork** [Evertrix/Twitter#4]
The developer must be able to use own database, which could be already existing. Therefore the database must not be created in the SQL setup file. Only the tables can be created (if not already existing) and the records can be inserted (if any).

This is the reason in db.php database name filed to be empty. There, the developer can set whatever database he/she choose.

So, please, remove the sql for database creating and setting in use.

`
CREATE DATABASE IF NOT EXISTS `twitter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE 'twitter';
`

**Comment by Evertrix** [comment]
It is done.
