### ISSUE TITLE
Unnecessary escaping

### ISSUE THREAD

**Issue by yasbaswork** [Evertrix/Twitter#6]
https://github.com/Evertrix/Twitter/blob/9aefb0b76e4494708535624930f343b700783eb5/index.php#L52

Why would you escape the double quote in every php echo command like this, instead of just using single quotes for wrapping the html strings in the echo statements, like this:

`
echo '<div class="tweet-wrap">'
`

???

**Comment by Evertrix** [comment]
Escapings cleared.
