### ISSUE TITLE
Delete button Issue

### ISSUE THREAD

**Issue by Evertrix** [Evertrix/Twitter#8]
Cannot configure properly a delete button for the tweets on dashboard.php

![Screenshot from 2019-12-31 11-53-13](https://user-images.githubusercontent.com/43696707/71617569-5356c000-2bc4-11ea-834a-8535b83d7852.png)
![Screenshot from 2019-12-31 11-53-50](https://user-images.githubusercontent.com/43696707/71617570-53ef5680-2bc4-11ea-9f72-77a6a8f3676b.png)

**Comment by yasbaswork** [comment]
You are opening a new PHP tag before closing the previous one ?! And do you really need to open PHP tag when you are already inside one. Copy/paste error again ? :)

**Comment by yasbaswork** [comment]
However this will not fix the issue as it's bigger.

You are not deleting the selected tweet, but all tweets of the user! Please, check pass only the tweet id to delete.php and in delete.php delete only the tweet with the received id.

**Comment by Evertrix** [comment]
It is fixed.

**Comment by yasbaswork** [comment]
Good. Now you can remove tweets on the profile page and add Delete buttons on the tweets located on the user's dashboard. This way, you won't have the same functionality (displaying user's tweets) on two pages, with the only difference being the delete button.

So, to summarize:

-  add delete button on the tweets located on dashboard page.
- remove tweets from profile page.

**Comment by yasbaswork** [comment]
OK.
