### ISSUE TITLE
Tweets not created on new installation.

### ISSUE THREAD

**Issue by yasbaswork** [Evertrix/Twitter#9]
If you clone the repo, setup the project and register an account and try to create a new tweet, it won't work. No tweet can be created. Please, investigate the issue.

**Comment by Evertrix** [comment]
Worked on me when restarting the apache2 server.

**Comment by yasbaswork** [comment]
What about on a new installation ??

**Comment by Evertrix** [comment]
New installation of what? Whan I clone and set up the project it all works fine after I restarted the server.

**Comment by Evertrix** [comment]
Problem is now fixed. Tested on another computer. 
Before:
![Annotation 2020-01-25 132108](https://user-images.githubusercontent.com/43696707/73120373-085d6d80-3f22-11ea-9512-f50756555518.png)

Now:
![Annotation 2020-01-25 132155](https://user-images.githubusercontent.com/43696707/73120374-11e6d580-3f22-11ea-9418-b65ebe04f51c.png)

**Comment by yasbaswork** [comment]
Actually the problem was with the not updated db setup file, the 'image' field was missing, but you pushed it meanwhile which fixed the issue.
